services:
  django:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - nodejs
      - mongo_db
    networks:
      - backend_network

  nodejs:
    build: ./database
    ports:
      - "3031:3030"
    depends_on:
      - mongo_db
    networks:
      - backend_network

  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend_network

volumes:
  mongo_data:

networks:
  backend_network:
    driver: bridge
