name: Lint

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  lint_js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          cd server/frontend
          npm install
      - name: Run ESLint
        run: |
          cd server/frontend
          npx eslint "src/**/*.{js,jsx}" --max-warnings=0 